# Generated by Django 3.2 on 2021-09-13 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='customer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('zip_code', models.CharField(max_length=90)),
                ('m_no', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('biling_name', models.CharField(default=0, max_length=50)),
                ('biling_mno', models.IntegerField(default=0)),
                ('biling_address', models.CharField(blank=True, default=0, max_length=60)),
                ('shipping_name', models.CharField(default=0, max_length=50)),
                ('shipping_mno', models.IntegerField(default=0)),
                ('shipping_address', models.CharField(blank=True, default=0, max_length=60)),
                ('status', models.CharField(choices=[('ORDER_WAITING', 'ORDER_WAITING'), ('ORDER_PLACED', 'ORDER_PLACED'), ('ORDER_ACCEPTED', 'ORDER_ACCEPTED'), ('ORDER_COMPLETED', 'ORDER_COMPLETED'), ('ORDER_CANCELLED', 'ORDER_CANCELLED'), ('ORDER_DISPATCHED', 'ORDER_DISPATCHED')], default='Waiting', max_length=50)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem')),
                ('orderedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
